server:
  port: 8080
  shutdown: graceful

spring:
  application:
    name: fulfillment-api
  lifecycle:
    timeout-per-shutdown-phase: 10s
  cloud:
    aws:
      region:
        static: us-east-1
      credentials:
        access-key: test
        secret-key: test
      sns:
        endpoint: http://localhost:4566
      sqs:
        endpoint: http://localhost:4566

  datasource:
    url: jdbc:postgresql://localhost:5432/fulfillment_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    baseline-on-migrate: true

axon:
  axonserver:
    enabled: false

springdoc:
  swagger-ui:
    path: /swagger-ui.html

logging:
  pattern:
    console: "%clr(%d{yyyy-MM-dd'T'HH:mm:ss}){faint} %clr(%5p) %clr([${spring.application.name:-}]){faint} %m%n%wEx"
  level:
    root: INFO
    org.springframework.web: WARN
    com.openmind: INFO
